services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Qc\QcWsPreviewLang\:
    resource: '../Classes/*'

  Qc\QcWsPreviewLang\Middleware\ExtendedWorkspacePreview:
    public: true